<?php

namespace MyCompany\ArticleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getUpcomingArticles(){

        return $this->createQueryBuilder('a')
            ->addOrderBy('a.time','DESC')
            ->andWhere('a.time > :now')
            ->setParameter('now', new \DateTime())
            ->getQuery()
            ->execute()
        ;
    }
}
