news_index:
    path:     /
    defaults: { _controller: "MyCompanyArticleBundle:Article:index" }
    methods:  GET

news_show:
    path:     /{id}/show
    defaults: { _controller: "MyCompanyArticleBundle:Article:show" }
    methods:  GET

news_new:
    path:     /new
    defaults: { _controller: "MyCompanyArticleBundle:Article:new" }
    methods:  [GET, POST]

news_edit:
    path:     /{id}/edit
    defaults: { _controller: "MyCompanyArticleBundle:Article:edit" }
    methods:  [GET, POST]

news_delete:
    path:     /{id}/delete
    defaults: { _controller: "MyCompanyArticleBundle:Article:delete" }
    methods:  DELETE
